import EMOptions from "com.hyphenate.chat.EMOptions";
import EMClient from "com.hyphenate.chat.EMClient";


export function initEMClient(appkey: string): void {
	const options = new EMOptions();
	// 设置环信AppKey
	options.setAppKey(appkey);
	// 关闭自动登录
	options.setAutoLogin(false);
	console.log(options.getAppKey(), 'getappkey')
	EMClient.getInstance().init(UTSAndroid.getAppContext(), options)
	// EMClient.getInstance().addConnectionListener(new ConnectioonListener());
	// EMClient.getInstance().chatManager().addMessageListener(new MessageListener());
}
