pluginManagement {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        flatDir { dirs('./plugins/') }
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        maven { url 'https://repo1.maven.org/maven2/' }
        flatDir { dirs('./plugins/') }
    }
}

rootProject.name = "EasemobUniAppX"
include ':app'
include ':uni_modules:easemob-im'
