import NZIMAudioMessage from 'im.zego.zim.entity.ZIMAudioMessage';
import NZIMAudioMessageLiteInfo from 'im.zego.zim.entity.ZIMAudioMessageLiteInfo';
import NZIMBarrageMessage from 'im.zego.zim.entity.ZIMBarrageMessage';
import NZIMCallInfo from 'im.zego.zim.entity.ZIMCallInfo';
import NZIMCallUserInfo from 'im.zego.zim.entity.ZIMCallUserInfo';
import NZIMCombineMessage from 'im.zego.zim.entity.ZIMCombineMessage';
import NZIMCombineMessageLiteInfo from 'im.zego.zim.entity.ZIMCombineMessageLiteInfo';
import NZIMCommandMessage from 'im.zego.zim.entity.ZIMCommandMessage';
import NZIMConversation from 'im.zego.zim.entity.ZIMConversation';
import NZIMConversationBaseInfo from 'im.zego.zim.entity.ZIMConversationBaseInfo';
import NZIMConversationChangeInfo from 'im.zego.zim.entity.ZIMConversationChangeInfo';
import NZIMConversationSearchInfo from 'im.zego.zim.entity.ZIMConversationSearchInfo';
import NZIMCustomMessage from 'im.zego.zim.entity.ZIMCustomMessage';
import NZIMCustomMessageLiteInfo from 'im.zego.zim.entity.ZIMCustomMessageLiteInfo';
import NZIMErrorUserInfo from 'im.zego.zim.entity.ZIMErrorUserInfo';
import NZIMFileMessage from 'im.zego.zim.entity.ZIMFileMessage';
import NZIMFileMessageLiteInfo from 'im.zego.zim.entity.ZIMFileMessageLiteInfo';
import NZIMFriendApplicationInfo from 'im.zego.zim.entity.ZIMFriendApplicationInfo';
import NZIMFriendInfo from 'im.zego.zim.entity.ZIMFriendInfo';
import NZIMFriendRelationInfo from 'im.zego.zim.entity.ZIMFriendRelationInfo';
import NZIMGroup from 'im.zego.zim.entity.ZIMGroup';
import NZIMGroupApplicationInfo from 'im.zego.zim.entity.ZIMGroupApplicationInfo';
import NZIMGroupAttributesUpdateInfo from 'im.zego.zim.entity.ZIMGroupAttributesUpdateInfo';
import NZIMGroupConversation from 'im.zego.zim.entity.ZIMGroupConversation';
import NZIMGroupFullInfo from 'im.zego.zim.entity.ZIMGroupFullInfo';
import NZIMGroupInfo from 'im.zego.zim.entity.ZIMGroupInfo';
import NZIMGroupMemberInfo from 'im.zego.zim.entity.ZIMGroupMemberInfo';
import NZIMGroupMemberSimpleInfo from 'im.zego.zim.entity.ZIMGroupMemberSimpleInfo';
import NZIMGroupMuteInfo from 'im.zego.zim.entity.ZIMGroupMuteInfo';
import NZIMGroupOperatedInfo from 'im.zego.zim.entity.ZIMGroupOperatedInfo';
import NZIMGroupSearchInfo from 'im.zego.zim.entity.ZIMGroupSearchInfo';
import NZIMGroupVerifyInfo from 'im.zego.zim.entity.ZIMGroupVerifyInfo';
import NZIMImageMessage from 'im.zego.zim.entity.ZIMImageMessage';
import NZIMImageMessageLiteInfo from 'im.zego.zim.entity.ZIMImageMessageLiteInfo';
import NZIMMediaMessage from 'im.zego.zim.entity.ZIMMediaMessage';
import NZIMMediaMessageLiteInfo from 'im.zego.zim.entity.ZIMMediaMessageLiteInfo';
import NZIMMessage from 'im.zego.zim.entity.ZIMMessage';
import NZIMMessageLiteInfo from 'im.zego.zim.entity.ZIMMessageLiteInfo';
import NZIMMessageMentionedInfo from 'im.zego.zim.entity.ZIMMessageMentionedInfo';
import NZIMMessageReaction from 'im.zego.zim.entity.ZIMMessageReaction';
import NZIMMessageReactionUserInfo from 'im.zego.zim.entity.ZIMMessageReactionUserInfo';
import NZIMMessageReceiptInfo from 'im.zego.zim.entity.ZIMMessageReceiptInfo';
import NZIMMessageRepliedInfo from 'im.zego.zim.entity.ZIMMessageRepliedInfo';
import NZIMMessageRootRepliedCountInfo from 'im.zego.zim.entity.ZIMMessageRootRepliedCountInfo';
import NZIMMessagePinStatusChangeInfo from 'im.zego.zim.entity.ZIMMessagePinStatusChangeInfo';
import NZIMMessageSearchConfig from 'im.zego.zim.entity.ZIMMessageSearchConfig';
import NZIMMessageSendConfig from 'im.zego.zim.entity.ZIMMessageSendConfig';
import NZIMMessageSentStatusChangeInfo from 'im.zego.zim.entity.ZIMMessageSentStatusChangeInfo';
import NZIMMultipleMessage from 'im.zego.zim.entity.ZIMMultipleMessage';
import NZIMMultipleMessageLiteInfo from 'im.zego.zim.entity.ZIMMultipleMessageLiteInfo';
import NZIMOfflinePushPrivateMessageTemplate from 'im.zego.zim.entity.ZIMOfflinePushPrivateMessageTemplate';
import NZIMPushConfig from 'im.zego.zim.entity.ZIMPushConfig';
import NZIMRevokeMessage from 'im.zego.zim.entity.ZIMRevokeMessage';
import NZIMRevokeMessageLiteInfo from 'im.zego.zim.entity.ZIMRevokeMessageLiteInfo';
import NZIMRoomAdvancedConfig from 'im.zego.zim.entity.ZIMRoomAdvancedConfig';
import NZIMRoomAttributesUpdateInfo from 'im.zego.zim.entity.ZIMRoomAttributesUpdateInfo';
import NZIMRoomFullInfo from 'im.zego.zim.entity.ZIMRoomFullInfo';
import NZIMRoomInfo from 'im.zego.zim.entity.ZIMRoomInfo';
import NZIMRoomMemberAttributesInfo from 'im.zego.zim.entity.ZIMRoomMemberAttributesInfo';
import NZIMRoomMemberAttributesOperatedInfo from 'im.zego.zim.entity.ZIMRoomMemberAttributesOperatedInfo';
import NZIMRoomMemberAttributesUpdateInfo from 'im.zego.zim.entity.ZIMRoomMemberAttributesUpdateInfo';
import NZIMRoomMemberInfo from 'im.zego.zim.entity.ZIMRoomMemberInfo';
import NZIMTextMessage from 'im.zego.zim.entity.ZIMTextMessage';
import NZIMTextMessageLiteInfo from 'im.zego.zim.entity.ZIMTextMessageLiteInfo';
import NZIMTipsMessage from 'im.zego.zim.entity.ZIMTipsMessage';
import NZIMTipsMessageChangeInfo from 'im.zego.zim.entity.ZIMTipsMessageChangeInfo';
import NZIMTipsMessageGroupChangeInfo from 'im.zego.zim.entity.ZIMTipsMessageGroupChangeInfo';
import NZIMTipsMessageGroupMemberChangeInfo from 'im.zego.zim.entity.ZIMTipsMessageGroupMemberChangeInfo';
import NZIMTipsMessagePinStatusChangeInfo from 'im.zego.zim.entity.ZIMTipsMessagePinStatusChangeInfo';
import NZIMUserFullInfo from 'im.zego.zim.entity.ZIMUserFullInfo';
import NZIMUserInfo from 'im.zego.zim.entity.ZIMUserInfo';
import NZIMUserOfflinePushRule from 'im.zego.zim.entity.ZIMUserOfflinePushRule';
import NZIMUserStatus from 'im.zego.zim.entity.ZIMUserStatus';
import NZIMUserStatusSubscription from 'im.zego.zim.entity.ZIMUserStatusSubscription';
import NZIMVideoMessage from 'im.zego.zim.entity.ZIMVideoMessage';
import NZIMVideoMessageLiteInfo from 'im.zego.zim.entity.ZIMVideoMessageLiteInfo';
import NZIMVoIPConfig from 'im.zego.zim.entity.ZIMVoIPConfig';

import NZIMConversationType from 'im.zego.zim.enums.ZIMConversationType';
import NZIMCXHandleType from 'im.zego.zim.enums.ZIMCXHandleType';
import NZIMMessageDirection from 'im.zego.zim.enums.ZIMMessageDirection';
import NZIMMessageOrder from 'im.zego.zim.enums.ZIMMessageOrder';
import NZIMMessagePriority from 'im.zego.zim.enums.ZIMMessagePriority';
import NZIMMessageReceiptStatus from 'im.zego.zim.enums.ZIMMessageReceiptStatus';
import NZIMMessageRepliedInfoState from 'im.zego.zim.enums.ZIMMessageRepliedInfoState';
import NZIMMessageRevokeStatus from 'im.zego.zim.enums.ZIMMessageRevokeStatus';
import NZIMMessageSentStatus from 'im.zego.zim.enums.ZIMMessageSentStatus';
import NZIMMessageType from 'im.zego.zim.enums.ZIMMessageType';
import NZIMPlatformType from 'im.zego.zim.enums.ZIMPlatformType';
import NZIMRevokeType from 'im.zego.zim.enums.ZIMRevokeType';
import NZIMTipsMessageEvent from 'im.zego.zim.enums.ZIMTipsMessageEvent';

import {
    ZIMCallInfo,
    ZIMCallUserInfo,
    ZIMConversation,
    ZIMConversationBaseInfo,
    ZIMConversationChangeInfo,
    ZIMConversationSearchInfo,
    ZIMConversationType,
    ZIMErrorUserInfo,
    ZIMFriendApplicationInfo,
    ZIMFriendInfo,
    ZIMFriendRelationInfo,
    ZIMGroup,
    ZIMGroupApplicationInfo,
    ZIMGroupAttributesUpdateInfo,
    ZIMGroupEnterInfo,
    ZIMGroupFullInfo,
    ZIMGroupInfo,
    ZIMGroupMemberInfo,
    ZIMGroupMemberSimpleInfo,
    ZIMGroupMuteInfo,
    ZIMGroupOperatedInfo,
    ZIMGroupSearchInfo,
    ZIMGroupVerifyInfo,
    ZIMMessage,
    ZIMMessageLiteInfo,
    ZIMMessageMentionedInfo,
    ZIMMessageReaction,
    ZIMMessageReactionUserInfo,
    ZIMMessageReceiptInfo,
    ZIMMessageRepliedInfo,
    ZIMMessageRootRepliedCountInfo,
    ZIMMessagePinStatusChangeInfo,
    ZIMMessageSearchConfig,
    ZIMMessageSendConfig,
    ZIMMessageSentStatusChangeInfo,
    ZIMMessageType,
    ZIMPlatformType,
    ZIMPushConfig,
    ZIMRoomAdvancedConfig,
    ZIMRoomAttributesUpdateInfo,
    ZIMRoomFullInfo,
    ZIMRoomInfo,
    ZIMRoomMemberAttributesInfo,
    ZIMRoomMemberAttributesOperatedInfo,
    ZIMRoomMemberAttributesUpdateInfo,
    ZIMRoomMemberInfo,
    ZIMTipsMessageChangeInfo,
    ZIMTipsMessageChangeInfoType,
    ZIMUserFullInfo,
    ZIMUserInfo,
    ZIMUserOfflinePushRule,
    ZIMUserStatus,
    ZIMUserStatusSubscription,
} from '../interface.uts';

const unCombineMessageTypes = [2, 20, 31, 32, 100];
const multipleMessageTypes = [1, 200, 11, 12, 13, 14];

// MARK: - Public

export const oMap = (json: UTSJSONObject): HashMap<string, string> => {
    const map: HashMap<string, string> = new HashMap<string, string>();
    for (const key in json) {
        map.put(key, json[key] as string);
    }

    return map;
};

export const mMap = (map: HashMap<string, string>) => {
    const json = {} as UTSJSONObject;
    for (const key in map.keys) {
        json[key] = map.get(key);
    }
    return json;
};

export const oStringArray = (infos: string[]): ArrayList<string> => {
    const _infos: ArrayList<string> = new ArrayList<string>();
    for (let i = 0; i < infos.length; i++) {
        _infos.add(infos[i]);
    }
    
    return _infos;
};

export const mStringArray = (infos: ArrayList<Long>): string[] => {
    const list: string[] = [];
    
    for (let i = 0; i < infos.size; i++) {
        list.push(infos.get(i as Int).toString());
    }
    
    return list;
};

export const oZIMPushConfig = (info: ZIMPushConfig): NZIMPushConfig => {
    const obj: NZIMPushConfig = new NZIMPushConfig();
    obj.title = info.title ?? '';
    obj.content = info.content ?? '';
    obj.payload = info.payload ?? '';
    obj.resourcesID = info.resourcesID ?? '';
    obj.badgeIncrement = (info.badgeIncrement ?? 0) as Int;
    obj.enableBadge = info.enableBadge ?? false;
    if (info.voIPConfig != null) {
        obj.voIPConfig = new NZIMVoIPConfig();
        obj.voIPConfig.iOSVoIPHandleType = NZIMCXHandleType.getZIMCXHandleType(
            info.voIPConfig!.iOSVoIPHandleType.toInt(),
        );
        obj.voIPConfig.iOSVoIPHandleValue = info.voIPConfig!.iOSVoIPHandleValue ?? '';
        obj.voIPConfig.iOSVoIPHasVideo = info.voIPConfig!.iOSVoIPHasVideo ?? false;
    }
    if (info.privateMessageTemplate != null) {
        obj.privateMessageTemplate = new NZIMOfflinePushPrivateMessageTemplate();
        obj.privateMessageTemplate.templateID = info.privateMessageTemplate!.templateID ?? '';
        obj.privateMessageTemplate.titleParameters = info.privateMessageTemplate!.titleParameters ?? '';
        obj.privateMessageTemplate.contentParameters = info.privateMessageTemplate!.contentParameters ?? '';
    }

    return obj;
};

export const mZIMPlatformTypeList = (infos: ArrayList<NZIMPlatformType>) => {
    const list: ZIMPlatformType[] = [];

    for (let i = 0; i < infos.size; i++) {
        list.push(infos.get(i as Int).value());
    }

    return list;
};

export const oZIMConversationTypeList = (infos: ZIMConversationType[]): ArrayList<NZIMConversationType> => {
    const _infos: ArrayList<NZIMConversationType> = new ArrayList<NZIMConversationType>();
    for (let i = 0; i < infos.length; i++) {
        _infos.add(NZIMConversationType.getZIMConversationType(infos[i].toInt()));
    }

    return _infos;
};

export const oZIMMessageTypeList = (infos: ZIMMessageType[]): ArrayList<NZIMMessageType> => {
    const _infos: ArrayList<NZIMMessageType> = new ArrayList<NZIMMessageType>();
    for (let i = 0; i < infos.length; i++) {
        _infos.add(NZIMMessageType.getZIMMessageType(infos[i].toInt()));
    }

    return _infos;
};

// MARK: - User

export const mZIMUserInfo = (info: NZIMUserInfo) => {
    return {
        userID: info.userID,
        userName: info.userName,
        userAvatarUrl: info.userAvatarUrl,
        userExtendedData: info.userExtendedData,
    } as ZIMUserInfo;
};

export const mZIMUserInfoList = (infos: ArrayList<NZIMUserInfo>) => {
    const list: ZIMUserInfo[] = [];

    for (let i = 0; i < infos.size; i++) {
        list.push(mZIMUserInfo(infos.get(i as Int)));
    }

    return list;
};

export const mZIMUserFullInfo = (info: NZIMUserFullInfo) => {
    return {
        baseInfo: mZIMUserInfo(info.baseInfo),
        extendedData: info.extendedData,
    } as ZIMUserFullInfo;
};

export const mZIMUserFullInfoList = (infos: ArrayList<NZIMUserFullInfo>) => {
    const list: ZIMUserFullInfo[] = [];

    for (let i = 0; i < infos.size; i++) {
        list.push(mZIMUserFullInfo(infos.get(i as Int)));
    }

    return list;
};

export const mZIMErrorUserInfoList = (infos: ArrayList<NZIMErrorUserInfo>) => {
    const list: ZIMErrorUserInfo[] = [];

    for (let i = 0; i < infos.size; i++) {
        const info = infos.get(i as Int);
        list.push({ userID: info.userID, reason: info.reason });
    }

    return list;
};

export const mZIMUserStatus = (info: NZIMUserStatus) => {
    return {
        userID: info.userID,
        customStatus: info.customStatus,
        onlineStatus: info.onlineStatus.value(),
        onlinePlatforms: mZIMPlatformTypeList(info.onlinePlatforms),
        lastUpdateTime: info.lastUpdateTime,
        lastOnlineStatusUpdateTime: info.lastOnlineStatusUpdateTime,
        lastCustomStatusUpdateTime: info.lastCustomStatusUpdateTime,
    } as ZIMUserStatus;
};

export const mZIMUserStatusList = (infos: ArrayList<NZIMUserStatus>) => {
    const list: ZIMUserStatus[] = [];

    for (let i = 0; i < infos.size; i++) {
        list.push(mZIMUserStatus(infos.get(i as Int)));
    }

    return list;
};

export const mZIMUserOfflinePushRule = (info: NZIMUserOfflinePushRule) => {
    return {
        onlinePlatforms: Array.fromNative(info.onlinePlatforms) as number[],
        notToReceiveOfflinePushPlatforms: Array.fromNative(info.notToReceiveOfflinePushPlatforms) as number[],
    } as ZIMUserOfflinePushRule;
};

export const mZIMUserStatusSubscriptionList = (infos: ArrayList<NZIMUserStatusSubscription>) => {
    const list: ZIMUserStatusSubscription[] = [];

    for (let i = 0; i < infos.size; i++) {
        const info = infos.get(i as Int);
        list.push({
            userStatus: mZIMUserStatus(info.userStatus),
            subscribeExpiredTime: info.subscribeExpiredTime,
        });
    }

    return list;
};

// MARK: - Conversation

export const oZIMConversation = (info: ZIMConversation): NZIMConversation => {
    const obj: NZIMConversation = new NZIMConversation();
    obj.conversationID = info.conversationID;
    obj.type = NZIMConversationType.getZIMConversationType(info.type.toInt());
    obj.orderKey = info.orderKey.toLong();

    return obj;
};

export const mZIMConversation = (info: NZIMConversation) => {
    const mentionedInfoList: ZIMMessageMentionedInfo[] = [];
    if (info.mentionedInfoList != null && info.mentionedInfoList.size > 0) {
        for (let i = 0; i < info.mentionedInfoList.size; i++) {
            const item: NZIMMessageMentionedInfo = info.mentionedInfoList.get(i as Int);
            mentionedInfoList.push({
                type: item.type.value(),
                fromUserID: item.fromUserID,
                messageID: item.messageID.toString(),
                messageSeq: item.messageSeq,
            });
        }
    }

    const map: ZIMConversation = {
        conversationID: info.conversationID,
        conversationName: info.conversationName,
        conversationAlias: info.conversationAlias,
        conversationAvatarUrl: info.conversationAvatarUrl,
        type: info.type.value(),
        notificationStatus: info.notificationStatus.value(),
        unreadMessageCount: info.unreadMessageCount,
        orderKey: info.orderKey,
        isPinned: info.isPinned,
        pinnedTime: info.pinnedTime,
        draft: info.draft,
        marks: Array.fromNative(info.marks) as number[],
        mentionedInfoList,
    };

    if (info.lastMessage != null) {
        map.lastMessage = mZIMMessage(info.lastMessage);
    }
    if (info instanceof NZIMGroupConversation) {
        map.isDisabled = info.isDisabled;
        map.mutedExpiredTime = info.mutedExpiredTime;
    }

    return map;
};

export const mZIMConversationList = (infos: ArrayList<NZIMConversation>) => {
    const list: ZIMConversation[] = [];

    for (let i = 0; i < infos.size; i++) {
        list.push(mZIMConversation(infos.get(i as Int)));
    }

    return list;
};

export const mZIMConversationChangeInfoList = (infos: ArrayList<NZIMConversationChangeInfo>) => {
    const list: ZIMConversationChangeInfo[] = [];

    for (let i = 0; i < infos.size; i++) {
        const info = infos.get(i as Int);
        list.push({ event: info.event.value(), conversation: mZIMConversation(info.conversation) });
    }

    return list;
};

export const oZIMConversationBaseInfoList = (infos: ZIMConversationBaseInfo[]): ArrayList<NZIMConversationBaseInfo> => {
    const _infos: ArrayList<NZIMConversationBaseInfo> = new ArrayList<NZIMConversationBaseInfo>();
    for (let i = 0; i < infos.length; i++) {
        const item = infos[i];
        const info = new NZIMConversationBaseInfo();
        info.conversationID = item.conversationID;
        info.conversationType = NZIMConversationType.getZIMConversationType(item.conversationType.toInt());
        _infos.add(info);        
    }
    return _infos;
};

export const mZIMConversationBaseInfoList = (infos: ArrayList<NZIMConversationBaseInfo>) => {
    const list: ZIMConversationBaseInfo[] = [];

    for (let i = 0; i < infos.size; i++) {
        const info = infos.get(i as Int);
        list.push({
            conversationID: info.conversationID,
            conversationType: info.conversationType.value(),
        });
    }

    return list;
};

// MARK: - Message

export const oZIMMessage = (info: ZIMMessage, isSend: boolean): NZIMMessage => {
    const type = info.type!;
    let obj = oZIMCombineMessage(info, isSend);
    // 合并消息子项
    if (unCombineMessageTypes.indexOf(type) == -1) {
        return obj;
    }
    
    // 根据消息类型赋值
    if (type == 2) {
        const bytes = info.message! as number[];
        const arr = new ByteArray(bytes.length as Int);
        for (let i = 0; i < bytes.length; i++) {
            arr[i as Int] = bytes[i].toByte();
        }
        obj = new NZIMCommandMessage(arr);
    } else if (type == 20) {
        obj = new NZIMBarrageMessage((info.message ?? '') as string);
    } else if (type == 31) {
        obj = new NZIMRevokeMessage();
        try {
            const clz = Class.forName('im.zego.zim.entity.ZIMRevokeMessage');
            
            let field = clz.getDeclaredField('revokeType');
            field.setAccessible(true);
            field.set(obj, NZIMRevokeType.getZIMRevokeType(info.revokeType!.toInt()));
            field.setAccessible(false);
            
            field = clz.getDeclaredField('revokeStatus');
            field.setAccessible(true);
            field.set(obj, NZIMMessageRevokeStatus.getZIMMessageRevokeStatus(info.revokeStatus!.toInt()));
            field.setAccessible(false);

            field = clz.getDeclaredField('originalMessageType');
            field.setAccessible(true);
            field.set(obj, NZIMMessageType.getZIMMessageType(info.originalMessageType!.toInt()));
            field.setAccessible(false);

            field = clz.getDeclaredField('originalTextMessageContent');
            field.setAccessible(true);
            field.set(obj, info.originalTextMessageContent ?? '');
            field.setAccessible(false);

            field = clz.getDeclaredField('revokeTimestamp');
            field.setAccessible(true);
            field.set(obj, info.revokeTimestamp ?? 0);
            field.setAccessible(false);

            field = clz.getDeclaredField('operatedUserID');
            field.setAccessible(true);
            field.set(obj, info.operatedUserID ?? '');
            field.setAccessible(false);

            field = clz.getDeclaredField('revokeExtendedData');
            field.setAccessible(true);
            field.set(obj, info.revokeExtendedData ?? '');
            field.setAccessible(false);
        } catch (error) {}
    } else if (type == 32) {
        const map = new NZIMTipsMessage();
        obj = map;
        map.event = NZIMTipsMessageEvent.getZIMTipsMessageEvent(info.event!.toInt());
        if (info.operatedUser != null) {
            map.operatedUser = oZIMUserOrGroupMember(info.operatedUser!);
        }
        if (info.targetUserList != null) {
            const _infos: ArrayList<NZIMUserInfo> = new ArrayList<NZIMUserInfo>();
            for (let i = 0; i < info.targetUserList!.length; i++) {
                _infos.add(oZIMUserOrGroupMember(info.targetUserList![i]));
            }
            map.targetUserList = _infos;
        }
        if (info.changeInfo != null) {
            map.changeInfo = oZIMTipsMessageChangeInfo(info.changeInfo!);
        }
    } else if (type == 100) {
        const messageList = new ArrayList<NZIMMessage>();
        if (info.messageList != null) {
            for (let i = 0; i < info.messageList!.length; i++) {
                const v = info.messageList![i];
                if (v.type == 100) {
                    const msg = new NZIMCombineMessage(v.title ?? '', v.summary ?? '', new ArrayList<NZIMMessage>());
                    try {
                        const clz = Class.forName('im.zego.zim.entity.ZIMCombineMessage');
                        
                        const field = clz.getDeclaredField('combineID');
                        field.setAccessible(true);
                        field.set(msg, v.combineID ?? '');
                        field.setAccessible(false);
                    } catch (error) {}
                    setZIMMessageValue(msg, v, isSend);
                    messageList.add(msg);
                } else {
                    messageList.add(oZIMCombineMessage(v, isSend));
                }
            }
        }
        obj = new NZIMCombineMessage(info.title ?? '', info.summary ?? '', messageList);
        try {
            const clz = Class.forName('im.zego.zim.entity.ZIMCombineMessage');
            
            const field = clz.getDeclaredField('combineID');
            field.setAccessible(true);
            field.set(obj, info.combineID ?? '');
            field.setAccessible(false);
        } catch (error) {}
    } 

    setZIMMessageValue(obj, info, isSend);
    
    return obj;
};
/**
 * Error: recursive problem
 */
const oZIMCombineMessage = (info: ZIMMessage, isSend: boolean): NZIMMessage => {
    const type = info.type;
    let obj: NZIMMessage = new NZIMMessage(NZIMMessageType.getZIMMessageType(type.toInt()));

    // 根据消息类型赋值
    if (type == 1) {
        obj = new NZIMTextMessage((info.message ?? '') as string);
    } else if (type == 200) {
        obj = new NZIMCustomMessage((info.message ?? '') as string, (info.subType ?? 0).toInt());
        (obj as NZIMCustomMessage).searchedContent = info.searchedContent ?? '';
    } else if (type == 10) {
        obj = new NZIMMultipleMessage();
        (obj as NZIMMultipleMessage).setMessageInfoList(oZIMMessageLiteInfoList(info.messageInfoList!));
    } else if (type == 11) {
        obj = new NZIMImageMessage((info.fileLocalPath ?? '') as string);
        (obj as NZIMImageMessage).setThumbnailDownloadUrl(info.thumbnailDownloadUrl ?? '');
        (obj as NZIMImageMessage).setLargeImageDownloadUrl(info.largeImageDownloadUrl ?? '');

        try {
            const clz = Class.forName('im.zego.zim.entity.ZIMImageMessage');
            
            let field = clz.getDeclaredField('thumbnailLocalPath');
            field.setAccessible(true);
            field.set(obj, info.thumbnailLocalPath ?? '');
            field.setAccessible(false);

            field = clz.getDeclaredField('largeImageLocalPath');
            field.setAccessible(true);
            field.set(obj, info.largeImageLocalPath ?? '');
            field.setAccessible(false);

            field = clz.getDeclaredField('originalImageWidth');
            field.setAccessible(true);
            field.set(obj, info.originalImageWidth ?? 0);
            field.setAccessible(false);

            field = clz.getDeclaredField('originalImageHeight');
            field.setAccessible(true);
            field.set(obj, info.originalImageHeight ?? 0);
            field.setAccessible(false);

            field = clz.getDeclaredField('thumbnailWidth');
            field.setAccessible(true);
            field.set(obj, info.thumbnailWidth ?? 0);
            field.setAccessible(false);

            field = clz.getDeclaredField('thumbnailHeight');
            field.setAccessible(true);
            field.set(obj, info.thumbnailHeight ?? 0);
            field.setAccessible(false);

            field = clz.getDeclaredField('largeImageWidth');
            field.setAccessible(true);
            field.set(obj, info.largeImageWidth ?? 0);
            field.setAccessible(false);

            field = clz.getDeclaredField('largeImageHeight');
            field.setAccessible(true);
            field.set(obj, info.largeImageHeight ?? 0);
            field.setAccessible(false);
        } catch (error) {}
    } else if (type == 12) {
        obj = new NZIMFileMessage((info.fileLocalPath ?? '') as string);
    } else if (type == 13) {
        obj = new NZIMAudioMessage((info.fileLocalPath ?? '') as string, (info.audioDuration ?? 0).toLong());
    } else if (type == 14) {
        obj = new NZIMVideoMessage((info.fileLocalPath ?? '') as string, (info.videoDuration ?? 0).toLong());

        try {
            const clz = Class.forName('im.zego.zim.entity.ZIMVideoMessage');
            
            let field = clz.getDeclaredField('videoFirstFrameDownloadUrl');
            field.setAccessible(true);
            field.set(obj, info.videoFirstFrameDownloadUrl ?? '');
            field.setAccessible(false);

            field = clz.getDeclaredField('videoFirstFrameLocalPath');
            field.setAccessible(true);
            field.set(obj, info.videoFirstFrameLocalPath ?? '');
            field.setAccessible(false);

            field = clz.getDeclaredField('videoFirstFrameWidth');
            field.setAccessible(true);
            field.set(obj, info.videoFirstFrameWidth ?? 0);
            field.setAccessible(false);

            field = clz.getDeclaredField('videoFirstFrameHeight');
            field.setAccessible(true);
            field.set(obj, info.videoFirstFrameHeight ?? 0);
            field.setAccessible(false);
        } catch (error) {}
    }

    if (obj instanceof NZIMMediaMessage) {
        try {
            (obj as NZIMMediaMessage).setFileDownloadUrl(info.fileDownloadUrl ?? '');

            const clz = Class.forName('im.zego.zim.entity.ZIMMediaMessage');
            
            let field = clz.getDeclaredField('fileUID');
            field.setAccessible(true);
            field.set(obj, info.fileUID ?? '');
            field.setAccessible(false);

            field = clz.getDeclaredField('fileName');
            field.setAccessible(true);
            field.set(obj, info.fileName ?? '');
            field.setAccessible(false);

            field = clz.getDeclaredField('fileSize');
            field.setAccessible(true);
            field.set(obj, info.fileSize ?? 0);
            field.setAccessible(false);
        } catch (error) {}
    }

    setZIMMessageValue(obj, info, isSend);
    
    return obj;
};
/**
 * 设置公共属性
 */
const setZIMMessageValue = (obj: NZIMMessage, info: ZIMMessage, isSend: boolean) => {
    if (info.mentionedUserIDs != null) {
        obj.setMentionedUserIDs(oStringArray(info.mentionedUserIDs!));    
    }
    obj.setIsMentionAll(info.isMentionAll ?? false);
    obj.extendedData = info.extendedData ?? '';
    obj.localExtendedData = info.localExtendedData ?? '';
    
    if (!isSend) {
        try {
            const clz = Class.forName('im.zego.zim.entity.ZIMMessage');
            
            let field = clz.getDeclaredField('messageID');
            field.setAccessible(true);
            field.set(obj, info.messageID != null && info.messageID != '' ? parseInt(info.messageID!, 10).toLong() : 0);
            field.setAccessible(false);
            
            field = clz.getDeclaredField('localMessageID');
            field.setAccessible(true);
            field.set(obj, info.localMessageID != null && info.localMessageID != '' ? parseInt(info.localMessageID!, 10).toLong() : 0);
            field.setAccessible(false);

            if (info.repliedInfo != null) {
                field = clz.getDeclaredField('repliedInfo');
                field.setAccessible(true);
                field.set(obj, oZIMMessageRepliedInfo(info.repliedInfo!));
                field.setAccessible(false);
            }

            field = clz.getDeclaredField('conversationType');
            field.setAccessible(true);
            field.set(obj, NZIMConversationType.getZIMConversationType(info.conversationType!.toInt()));
            field.setAccessible(false);
                
            field = clz.getDeclaredField('direction');
            field.setAccessible(true);
            field.set(obj, NZIMMessageDirection.getZIMMessageDirection(info.direction!.toInt()));
            field.setAccessible(false);
                
            field = clz.getDeclaredField('sentStatus');
            field.setAccessible(true);
            field.set(obj, NZIMMessageSentStatus.getZIMMessageSentStatus(info.sentStatus!.toInt()));
            field.setAccessible(false);
                
            field = clz.getDeclaredField('receiptStatus');
            field.setAccessible(true);
            field.set(obj, NZIMMessageReceiptStatus.getZIMMessageReceiptStatus(info.receiptStatus!.toInt()));
            field.setAccessible(false);

            field = clz.getDeclaredField('isUserInserted');
            field.setAccessible(true);
            field.set(obj, info.isUserInserted ?? false);
            field.setAccessible(false);
                
            field = clz.getDeclaredField('isServerMessage');
            field.setAccessible(true);
            field.set(obj, info.isServerMessage ?? false);
            field.setAccessible(false);
            
            field = clz.getDeclaredField('isBroadcastMessage');
            field.setAccessible(true);
            field.set(obj, info.isBroadcastMessage ?? false);
            field.setAccessible(false);
            
            field = clz.getDeclaredField('isGroupTargetedMessage');
            field.setAccessible(true);
            field.set(obj, info.isGroupTargetedMessage ?? false);
            field.setAccessible(false);
                  
            field = clz.getDeclaredField('messageSeq');
            field.setAccessible(true);
            field.set(obj, info.messageSeq ?? 0);
            field.setAccessible(false);
            field = clz.getDeclaredField('conversationSeq');
            field.setAccessible(true);
            field.set(obj, info.messageSeq ?? 0);
            field.setAccessible(false);
                
            field = clz.getDeclaredField('orderKey');
            field.setAccessible(true);
            field.set(obj, info.orderKey ?? 0);
            field.setAccessible(false);

            field = clz.getDeclaredField('timestamp');
            field.setAccessible(true);
            field.set(obj, info.timestamp ?? 0);
            field.setAccessible(false);

            field = clz.getDeclaredField('rootRepliedCount');
            field.setAccessible(true);
            field.set(obj, info.rootRepliedCount ?? 0);
            field.setAccessible(false);

            field = clz.getDeclaredField('editedTime');
            field.setAccessible(true);
            field.set(obj, info.editedTime ?? 0);
            field.setAccessible(false);

            field = clz.getDeclaredField('editorUserID');
            field.setAccessible(true);
            field.set(obj, info.editorUserID ?? '');
            field.setAccessible(false);

            field = clz.getDeclaredField('pinnedTime');
            field.setAccessible(true);
            field.set(obj, info.pinnedTime ?? 0);
            field.setAccessible(false);

            field = clz.getDeclaredField('pinnedUserID');
            field.setAccessible(true);
            field.set(obj, info.pinnedUserID ?? '');
            field.setAccessible(false);
            
            field = clz.getDeclaredField('senderUserID');
            field.setAccessible(true);
            field.set(obj, info.senderUserID ?? '');
            field.setAccessible(false);

            field = clz.getDeclaredField('conversationID');
            field.setAccessible(true);
            field.set(obj, info.conversationID ?? '');
            field.setAccessible(false);
        } catch (error) {}
    }    
}

export const mZIMMessage = (info: NZIMMessage) => {
    const type = info.getType().value() as ZIMMessageType;
    const map = mZIMCombineMessage(info);
    // 合并消息子项
    if (unCombineMessageTypes.indexOf(type) == -1) {
        return map;
    }

    // 根据消息类型赋值
    if (type == 2) {
        const bytes: number[] = [];
        const arr = Array.fromNative((info as NZIMCommandMessage).message) as ArrayList<number>;
        for (let i = 0; i < arr.size; i++) {
            let b = arr.get(i as Int);
            bytes.push(b < 0 ? 256 + b : b);
        }
        map.message = bytes;
    } else if (type == 20) {
        map.message = (info as NZIMBarrageMessage).message;
    } else if (type == 31) {
        const _info = info as NZIMRevokeMessage;
        map.revokeType = _info.getRevokeType().value();
        map.revokeStatus = _info.getRevokeStatus().value();
        map.originalMessageType = _info.getOriginalMessageType().value();
        map.originalTextMessageContent = _info.getOriginalTextMessageContent();
        map.revokeTimestamp = _info.getRevokeTimestamp();
        map.operatedUserID = _info.getOperatedUserID();
        map.revokeExtendedData = _info.getRevokeExtendedData();
    } else if (type == 32) {
        const _info = info as NZIMTipsMessage;
        map.event = _info.event.value();
        map.operatedUser = mZIMUserOrGroupMember(_info.operatedUser);
        map.targetUserList = mZIMUserOrGroupMemberList(_info.targetUserList);
        if (_info.changeInfo != null) { 
            map.changeInfo = mZIMTipsMessageChangeInfo(_info.changeInfo!);
        }
    } else if (type == 100) {
        const _info = info as NZIMCombineMessage;
        map.title = _info.title;
        map.summary = _info.summary;
        map.combineID = _info.getCombineID();
        
        const list: ZIMMessage[] = [];
        for (let i = 0; i < _info.messageList.size; i++) {
            const v = _info.messageList.get(i as Int) as NZIMMessage;
            const msg = mZIMCombineMessage(v);
            if (msg.type == 100) {
                const _v = v as NZIMCombineMessage;
                msg.title = _v.title;
                msg.summary = _v.summary;
                msg.combineID = _v.getCombineID();
                msg.messageList = [];
            }
            list.push(msg);
        }
        map.messageList = list;
    }

    return map;
};
/**
 * Error: recursive problem
 */
const mZIMCombineMessage = (info: NZIMMessage) => {
    const type = info.getType().value() as ZIMMessageType;
    const map = { type } as ZIMMessage;

    // 公共属性
    const messageID = info.getMessageID().toString();
    map.extendedData = info.extendedData;
    map.localExtendedData = info.localExtendedData;
    map.isMentionAll = info.isMentionAll();
    map.mentionedUserIDs = Array.fromNative(info.getMentionedUserIDs()) as string[];
    map.messageID = messageID.length > 1 ? messageID : '';
    map.localMessageID = info.getLocalMessageID().toString();
    map.senderUserID = info.getSenderUserID();
    map.timestamp = info.getTimestamp();
    map.messageSeq = info.getMessageSeq();
    map.orderKey = info.getOrderKey();
    map.conversationID = info.getConversationID();
    map.conversationType = info.getConversationType().value();
    map.direction = info.getDirection().value();
    map.sentStatus = info.getSentStatus().value();
    map.receiptStatus = info.getReceiptStatus().value();
    map.isUserInserted = info.isUserInserted();
    map.isServerMessage = info.isServerMessage();
    map.isBroadcastMessage = info.isBroadcastMessage();
    map.isGroupTargetedMessage = info.isGroupTargetedMessage();
    map.reactions = mZIMMessageReactionList(info.getReactions());
    map.rootRepliedCount = info.getRootRepliedCount();
    map.editorUserID = info.getEditorUserID();
    map.editedTime = info.getEditedTime();
    map.pinnedUserID = info.getPinnedUserID();
    map.pinnedTime = info.getPinnedTime();
    const repliedInfo = info.getRepliedInfo();
    if (repliedInfo != null) {
        map.repliedInfo = mZIMMessageRepliedInfo(repliedInfo!);
    }

    // 根据消息类型赋值
    if (type == 1) {
        map.message = (info as NZIMTextMessage).message;
    } else if (type == 200) {
        const _info = info as NZIMCustomMessage;
        map.message = _info.message;
        map.subType = _info.subType;
        map.searchedContent = _info.searchedContent;
    } else if (type == 10) {
        map.messageInfoList = mZIMMessageLiteInfoList((info as NZIMMultipleMessage).getMessageInfoList());
    } else if (type == 11) {
        const _info = info as NZIMImageMessage;
        map.thumbnailDownloadUrl = _info.getThumbnailDownloadUrl();
        map.thumbnailLocalPath = _info.getThumbnailLocalPath();
        map.largeImageDownloadUrl = _info.getLargeImageDownloadUrl();
        map.largeImageLocalPath = _info.getLargeImageLocalPath();
        map.originalImageWidth = _info.getOriginalImageWidth();
        map.originalImageHeight = _info.getOriginalImageHeight();
        map.thumbnailWidth = _info.getThumbnailWidth();
        map.thumbnailHeight = _info.getThumbnailHeight();
        map.largeImageWidth = _info.getLargeImageWidth();
        map.largeImageHeight = _info.getLargeImageHeight();
    } else if (type == 13) {
        map.audioDuration = (info as NZIMAudioMessage).getAudioDuration();
    } else if (type == 14) {
        const _info = info as NZIMVideoMessage;
        map.videoDuration = _info.getVideoDuration();
        map.videoFirstFrameDownloadUrl = _info.getVideoFirstFrameDownloadUrl();
        map.videoFirstFrameLocalPath = _info.getVideoFirstFrameLocalPath();
        map.videoFirstFrameWidth = _info.getVideoFirstFrameWidth();
        map.videoFirstFrameHeight = _info.getVideoFirstFrameHeight();
    }

    if (info instanceof NZIMMediaMessage) {
        const _info = info as NZIMMediaMessage;
        map.fileDownloadUrl = _info.getFileDownloadUrl();
        map.fileLocalPath = _info.getFileLocalPath();
        map.fileUID = _info.getFileUID();
        map.fileName = _info.getFileName();
        map.fileSize = _info.getFileSize();
    }

    return map;
};

export const oZIMMessageLiteInfo = (info: ZIMMessageLiteInfo): NZIMMessageLiteInfo => {
    const type = info.type!;
    let obj = oZIMMultipleMessageLiteInfo(info);
    // 组合消息子项
    if (multipleMessageTypes.indexOf(type) != -1) {
        return obj;
    }

    // 根据消息类型赋值
    if (type == 31) {
        obj = new NZIMRevokeMessageLiteInfo();
    } else if (type == 100) {
        obj = new NZIMCombineMessageLiteInfo();
        (obj as NZIMCombineMessageLiteInfo).title = info.title ?? '';
        (obj as NZIMCombineMessageLiteInfo).summary = info.summary ?? '';
    } else if (type == 10) {
        obj = new NZIMMultipleMessageLiteInfo();
        if (info.messageInfoList != null) {            
            const _infos: ArrayList<NZIMMessageLiteInfo> = new ArrayList<NZIMMessageLiteInfo>();
            for (let i = 0; i < info.messageInfoList!.length; i++) {
                _infos.add(oZIMMultipleMessageLiteInfo(info.messageInfoList![i]));
            }
            (obj as NZIMMultipleMessageLiteInfo).messageInfoList = _infos;
        }
    }
    
    return obj;
};
/**
 * Error: recursive problem
 */
const oZIMMultipleMessageLiteInfo = (info: ZIMMessageLiteInfo): NZIMMessageLiteInfo => {
    let obj: NZIMMessageLiteInfo = new NZIMMessageLiteInfo();

    // 根据消息类型赋值
    const type = info.type;
    if (type == 1) {
        obj = new NZIMTextMessageLiteInfo();
        (obj as NZIMTextMessageLiteInfo).message = info.message ?? '';
    } else if (type == 200) {
        const map = new NZIMCustomMessageLiteInfo();
        obj = map;
        map.message = info.message ?? '';
        map.subType = (info.subType ?? 0) as Int;
        map.searchedContent = info.searchedContent ?? '';
    } else if (type == 11) {
        const map = new NZIMImageMessageLiteInfo();
        obj = map;
        map.thumbnailDownloadUrl = info.thumbnailDownloadUrl ?? '';
        map.thumbnailLocalPath = info.thumbnailLocalPath ?? '';
        map.largeImageDownloadUrl = info.largeImageDownloadUrl ?? '';
        map.largeImageLocalPath = info.largeImageLocalPath ?? '';
        map.originalImageWidth = (info.originalImageWidth ?? 0) as Int;
        map.originalImageHeight = (info.originalImageHeight ?? 0) as Int;
        map.thumbnailWidth = (info.thumbnailWidth ?? 0) as Int;
        map.thumbnailHeight = (info.thumbnailHeight ?? 0) as Int;
        map.largeImageWidth = (info.largeImageWidth ?? 0) as Int;
        map.largeImageHeight = (info.largeImageHeight ?? 0) as Int;
    } else if (type == 12) {
        obj = new NZIMFileMessageLiteInfo();
    } else if (type == 13) {
        obj = new NZIMAudioMessageLiteInfo();
        (obj as NZIMAudioMessageLiteInfo).audioDuration = (info.audioDuration ?? 0).toLong();
    } else if (type == 14) {
        const map = new NZIMVideoMessageLiteInfo();
        obj = map;
        map.videoDuration = (info.videoDuration ?? 0).toLong();
        map.videoFirstFrameDownloadUrl = info.videoFirstFrameDownloadUrl ?? '';
        map.videoFirstFrameLocalPath = info.videoFirstFrameLocalPath ?? '';
        map.videoFirstFrameWidth = (info.videoFirstFrameWidth ?? 0) as Int;
        map.videoFirstFrameHeight = (info.videoFirstFrameHeight ?? 0) as Int;
    }

    if (obj instanceof NZIMMediaMessageLiteInfo) {
        const map = obj as NZIMMediaMessageLiteInfo;
        map.fileDownloadUrl = info.fileDownloadUrl ?? '';
        map.fileLocalPath = (info.fileLocalPath ?? '') as string;
        map.fileName = info.fileName ?? '';
        map.fileSize = (info.fileSize ?? 0).toLong();
    }

    return obj;
};

export const mZIMMessageLiteInfo = (info: NZIMMessageLiteInfo) => {
    const type = info.type.value() as ZIMMessageType;
    const map = mZIMMultipleMessageLiteInfo(info);
    // 组合消息子项
    if (multipleMessageTypes.indexOf(type) != -1) {
        return map;
    }

    // 根据消息类型赋值
    if (type == 100) {
        map.title = (info as NZIMCombineMessageLiteInfo).title;
        map.summary = (info as NZIMCombineMessageLiteInfo).summary;
    } else if (type == 10) {
        const infos = (info as NZIMMultipleMessageLiteInfo).messageInfoList as ArrayList<NZIMMessageLiteInfo>;
        const list: ZIMMessageLiteInfo[] = [];
        for (let i = 0; i < infos.size; i++) {
            list.push(mZIMMultipleMessageLiteInfo(infos.get(i as Int)));
        }
        map.messageInfoList = list;
    }

    return map;
};
/**
 * Error: recursive problem
 */
const mZIMMultipleMessageLiteInfo = (info: NZIMMessageLiteInfo) => {
    const type = info.type.value() as ZIMMessageType;
    const map = { type } as ZIMMessageLiteInfo;

    // 根据消息类型赋值
    if (type == 1) {
        map.message = (info as NZIMTextMessageLiteInfo).message;
    } else if (type == 200) {
        const _info = info as NZIMCustomMessageLiteInfo;
        map.message = _info.message;
        map.subType = _info.subType;
        map.searchedContent = _info.searchedContent;
    } else if (type == 11) {
        const _info = info as NZIMImageMessageLiteInfo;
        map.thumbnailDownloadUrl = _info.thumbnailDownloadUrl;
        map.thumbnailLocalPath = _info.thumbnailLocalPath;
        map.largeImageDownloadUrl = _info.largeImageDownloadUrl;
        map.largeImageLocalPath = _info.largeImageLocalPath;
        map.originalImageWidth = _info.originalImageWidth;
        map.originalImageHeight = _info.originalImageHeight;
        map.thumbnailWidth = _info.thumbnailWidth;
        map.thumbnailHeight = _info.thumbnailHeight;
        map.largeImageWidth = _info.largeImageWidth;
        map.largeImageHeight = _info.largeImageHeight;
    } else if (type == 13) {
        map.audioDuration = (info as NZIMAudioMessageLiteInfo).audioDuration;
    } else if (type == 14) {
        const _info = info as NZIMVideoMessageLiteInfo;
        map.videoDuration = _info.videoDuration;
        map.videoFirstFrameDownloadUrl = _info.videoFirstFrameDownloadUrl;
        map.videoFirstFrameLocalPath = _info.videoFirstFrameLocalPath;
        map.videoFirstFrameWidth = _info.videoFirstFrameWidth;
        map.videoFirstFrameHeight = _info.videoFirstFrameHeight;
    }

    if (info instanceof NZIMMediaMessageLiteInfo) {
        const _info = info as NZIMMediaMessageLiteInfo;
        map.fileDownloadUrl = _info.fileDownloadUrl;
        map.fileLocalPath = _info.fileLocalPath;
        map.fileName = _info.fileName;
        map.fileSize = _info.fileSize;
    }

    return map;
};

export const oZIMMessageList = (infos: ZIMMessage[]): ArrayList<NZIMMessage> => {
    const _infos: ArrayList<NZIMMessage> = new ArrayList<NZIMMessage>();
    for (let i = 0; i < infos.length; i++) {
        _infos.add(oZIMMessage(infos[i], false));
    }

    return _infos;
};

export const mZIMMessageList = (infos: ArrayList<NZIMMessage>) => {
    const list: ZIMMessage[] = [];

    for (let i = 0; i < infos.size; i++) {
        list.push(mZIMMessage(infos.get(i as Int)));
    }

    return list;
};

export const oZIMMessageLiteInfoList = (infos: ZIMMessageLiteInfo[]): ArrayList<NZIMMessageLiteInfo> => {
    const _infos: ArrayList<NZIMMessageLiteInfo> = new ArrayList<NZIMMessageLiteInfo>();
    for (let i = 0; i < infos.length; i++) {
        _infos.add(oZIMMessageLiteInfo(infos[i]));
    }

    return _infos;
};

export const mZIMMessageLiteInfoList = (infos: ArrayList<NZIMMessageLiteInfo>) => {
    const list: ZIMMessageLiteInfo[] = [];

    for (let i = 0; i < infos.size; i++) {
        list.push(mZIMMessageLiteInfo(infos.get(i as Int)));
    }

    return list;
};

export const mZIMMessageSentStatusChangeInfoList = (infos: ArrayList<NZIMMessageSentStatusChangeInfo>) => {
    const list: ZIMMessageSentStatusChangeInfo[] = [];

    for (let i = 0; i < infos.size; i++) {
        const info = infos.get(i as Int);
        list.push({ reason: info.reason, status: info.status.value(), message: mZIMMessage(info.message) });
    }

    return list;
};

export const mZIMMessageReactionUserInfoList = (infos: ArrayList<NZIMMessageReactionUserInfo>) => {
    const list: ZIMMessageReactionUserInfo[] = [];

    for (let i = 0; i < infos.size; i++) {
        list.push({ userID: infos.get(i as Int).userID });
    }

    return list;
};

export const mZIMMessageReaction = (info: NZIMMessageReaction) => {
    return {
        conversationID: info.conversationID,
        conversationType: info.conversationType.value(),
        reactionType: info.reactionType,
        isSelfIncluded: info.isSelfIncluded,
        messageID: info.messageID.toString(),
        totalCount: info.totalCount,
        userList: mZIMMessageReactionUserInfoList(info.userList),
    } as ZIMMessageReaction;
};

export const mZIMMessageReactionList = (infos: ArrayList<NZIMMessageReaction>) => {
    const list: ZIMMessageReaction[] = [];

    for (let i = 0; i < infos.size; i++) {
        list.push(mZIMMessageReaction(infos.get(i as Int)));
    }

    return list;
};

export const mZIMMessageReceiptInfoList = (infos: ArrayList<NZIMMessageReceiptInfo>) => {
    const list: ZIMMessageReceiptInfo[] = [];

    for (let i = 0; i < infos.size; i++) {
        const info = infos.get(i as Int);
        list.push({
            conversationID: info.conversationID,
            conversationType: info.conversationType.value(),
            status: info.status.value(),
            messageID: info.messageID.toString(),
            readMemberCount: info.readMemberCount,
            unreadMemberCount: info.unreadMemberCount,
            isSelfOperated: info.isSelfOperated,
            readTime: info.readTime.toLong(),
        });
    }

    return list;
};

export const oZIMMessageRepliedInfo = (info: ZIMMessageRepliedInfo): NZIMMessageRepliedInfo => {
    const obj = new NZIMMessageRepliedInfo();
    obj.state = NZIMMessageRepliedInfoState.getZIMMessageRepliedInfoState(info.state.toInt());
    obj.messageSeq = info.messageSeq.toLong();
    obj.messageID = info.messageID.toLong();
    obj.sentTime = info.sentTime.toLong();
    obj.senderUserID = info.senderUserID;
    obj.messageInfo = oZIMMessageLiteInfo(info.messageInfo);
    return obj;
};

export const mZIMMessageRepliedInfo = (info: NZIMMessageRepliedInfo) => {
    return {
        state: info.state.value(),
        messageSeq: info.messageSeq,
        messageID: info.messageID.toString(),
        senderUserID: info.senderUserID,
        sentTime: info.sentTime,
        messageInfo: mZIMMessageLiteInfo(info.messageInfo),
    } as ZIMMessageRepliedInfo;
};

export const mZIMMessageRootRepliedCountInfoList = (infos: ArrayList<NZIMMessageRootRepliedCountInfo>) => {
    const list: ZIMMessageRootRepliedCountInfo[] = [];

    for (let i = 0; i < infos.size; i++) {
        const info = infos.get(i as Int);
        list.push({
            conversationID: info.conversationID,
            conversationType: info.conversationType.value(),
            count: info.count,
            messageID: info.messageID.toString(),
        });
    }

    return list;
};

export const mZIMMessagePinStatusChangeInfoList = (infos: ArrayList<NZIMMessagePinStatusChangeInfo>) => {
    const list: ZIMMessagePinStatusChangeInfo[] = [];

    for (let i = 0; i < infos.size; i++) {
        const info = infos.get(i as Int);
        list.push({
            pinStatus: info.getPinStatus().value(),
            message: mZIMMessage(info.getMessage()),
        });
    }

    return list;
};

export const oZIMTipsMessageChangeInfo = (info: ZIMTipsMessageChangeInfo): NZIMTipsMessageChangeInfo => {
    const type = info.type;
    if (type < 10) {
        return new NZIMTipsMessageGroupChangeInfo();
    } else if (type >= 10 && type < 20) {
        return new NZIMTipsMessageGroupMemberChangeInfo();
    } else if (type == 21) {
        return new NZIMTipsMessagePinStatusChangeInfo();
    }
    return new NZIMTipsMessageChangeInfo();
};

export const mZIMTipsMessageChangeInfo = (info: NZIMTipsMessageChangeInfo) => {
    const type = info.type.value() as ZIMTipsMessageChangeInfoType;
    const map = { type } as ZIMTipsMessageChangeInfo;
    if (type < 10) {
        const _info = info as NZIMTipsMessageGroupChangeInfo;
        map.groupDataFlag = _info.groupDataFlag;
        map.groupName = _info.groupName;
        map.groupAvatarUrl = _info.groupAvatarUrl;
        map.groupNotice = _info.groupNotice;
        if (_info.groupMutedInfo != null) {
            map.groupMutedInfo = mZIMGroupMuteInfo(_info.groupMutedInfo!);
        }
    } else if (type >= 10 && type < 20) {
        const _info = info as NZIMTipsMessageGroupMemberChangeInfo;
        map.memberRole = _info.memberRole;
        map.muteExpiredTime = _info.muteExpiredTime;
        if (_info.groupNewOwner != null) {
            map.groupNewOwner = mZIMGroupMemberSimpleInfo(_info.groupNewOwner!);
        }
    } else if (type == 21) {
        const _info = info as NZIMTipsMessagePinStatusChangeInfo;
        map.isPinned = _info.isPinned;
    }
    return map;
};

export const mZIMConversationSearchInfoList = (infos: ArrayList<NZIMConversationSearchInfo>) => {
    const list: ZIMConversationSearchInfo[] = [];

    for (let i = 0; i < infos.size; i++) {
        const info = infos.get(i as Int);
        list.push({
            conversationID: info.conversationID,
            conversationType: info.conversationType.value(),
            totalMessageCount: info.totalMessageCount,
            messageList: mZIMMessageList(info.messageList),
        });
    }

    return list;
};

export const oZIMMessageSendConfig = (config: ZIMMessageSendConfig): NZIMMessageSendConfig => {
    const _config: NZIMMessageSendConfig = new NZIMMessageSendConfig();
    _config.priority = NZIMMessagePriority.getZIMMessagePriority(config.priority.toInt());
    _config.hasReceipt = config.hasReceipt ?? false;
    _config.isRetrySend = config.isRetrySend ?? false;
    _config.isNotifyMentionedUsers = config.isNotifyMentionedUsers ?? true;
    _config.disableUnreadMessageCount = config.disableUnreadMessageCount ?? false;
    if (config.pushConfig != null) {
        _config.pushConfig = oZIMPushConfig(config.pushConfig!);
    }
    return _config;
};

export const oZIMMessageSearchConfig = (config: ZIMMessageSearchConfig, nextMessageMap: Map<string, NZIMMessage>): NZIMMessageSearchConfig => {
    const _config: NZIMMessageSearchConfig = new NZIMMessageSearchConfig();
    _config.keywords = config.keywords ?? [];
    _config.senderUserIDs = config.senderUserIDs ?? [];
    _config.subMessageTypes = (config.subMessageTypes ?? []) as ArrayList<Int>;
    _config.messageTypes = oZIMMessageTypeList(config.messageTypes ?? []);
    _config.startTime = (config.startTime ?? 0).toLong();
    _config.endTime = (config.endTime ?? 0).toLong();
    _config.count = (config.count ?? 0) as Int;
    _config.order = NZIMMessageOrder.getZIMMessageOrder((config.order ?? 0).toInt());
    if (config.nextMessage != null) {
        _config.nextMessage = nextMessageMap.get(config.nextMessage!);
    }
    return _config;
};

// MARK: - Room

export const mZIMRoomFullInfo = (info: NZIMRoomFullInfo) => {
    return {
        baseInfo: {
            roomID: info.baseInfo.roomID,
            roomName: info.baseInfo.roomName,
        },
    } as ZIMRoomFullInfo;
};

export const mZIMRoomMemberInfoList = (infos: ArrayList<NZIMRoomMemberInfo>) => {
    const list: ZIMRoomMemberInfo[] = [];

    for (let i = 0; i < infos.size; i++) {
        const info = infos.get(i as Int);
        list.push({ userID: info.userID, userName: info.userName, userAvatarUrl: info.userAvatarUrl, userExtendedData: info.userExtendedData });
    }

    return list;
};

export const mZIMRoomMemberAttributesInfo = (info: NZIMRoomMemberAttributesInfo) => {
    return {
        userID: info.userID,
        attributes: mMap(info.attributes),
    } as ZIMRoomMemberAttributesInfo;
};

export const mZIMRoomMemberAttributesInfoList = (infos: ArrayList<NZIMRoomMemberAttributesInfo>) => {
    const list: ZIMRoomMemberAttributesInfo[] = [];

    for (let i = 0; i < infos.size; i++) {
        list.push(mZIMRoomMemberAttributesInfo(infos.get(i as Int)));
    }

    return list;
};

export const mZIMRoomAttributesUpdateInfoList = (infos: ArrayList<NZIMRoomAttributesUpdateInfo>) => {
    const list: ZIMRoomAttributesUpdateInfo[] = [];

    for (let i = 0; i < infos.size; i++) {
        const info = infos.get(i as Int);
        list.push({ action: info.action.value(), roomAttributes: mMap(info.roomAttributes) });
    }

    return list;
};

export const mZIMRoomMemberAttributesUpdateInfoList = (infos: ArrayList<NZIMRoomMemberAttributesUpdateInfo>) => {
    const list: ZIMRoomMemberAttributesUpdateInfo[] = [];

    for (let i = 0; i < infos.size; i++) {
        list.push({ attributesInfo: mZIMRoomMemberAttributesInfo(infos.get(i as Int).attributesInfo) });
    }

    return list;
};

export const mZIMRoomMemberAttributesOperatedInfoList = (infos: ArrayList<NZIMRoomMemberAttributesOperatedInfo>) => {
    const list: ZIMRoomMemberAttributesOperatedInfo[] = [];

    for (let i = 0; i < infos.size; i++) {
        const info = infos.get(i as Int);
        list.push({
            attributesInfo: mZIMRoomMemberAttributesInfo(info.attributesInfo),
            errorKeys: Array.fromNative(info.errorKeys) as string[],
        });
    }

    return list;
};

export const oZIMRoomInfo = (info: ZIMRoomInfo): NZIMRoomInfo => {
    const obj: NZIMRoomInfo = new NZIMRoomInfo();
    obj.roomID = info.roomID;
    obj.roomName = info.roomName;
    return obj;
};

export const oZIMRoomAdvancedConfig = (config?: ZIMRoomAdvancedConfig): NZIMRoomAdvancedConfig => {
    const _config: NZIMRoomAdvancedConfig = new NZIMRoomAdvancedConfig();
    if (config != null) {
        _config.roomAttributes = oMap(config!.roomAttributes ?? {});
        _config.roomDestroyDelayTime = (config!.roomDestroyDelayTime ?? 0) as Int;
    }
    return _config;
};

// MARK: - Group

export const mZIMGroupInfo = (info: NZIMGroupInfo) => {
    return {
        groupID: info.groupID,
        groupName: info.groupName,
        groupAvatarUrl: info.groupAvatarUrl,
    } as ZIMGroupInfo;
};

export const mZIMGroupList = (infos: ArrayList<NZIMGroup>) => {
    const list: ZIMGroup[] = [];

    for (let i = 0; i < infos.size; i++) {
        const info = infos.get(i as Int);
        list.push({
            baseInfo: mZIMGroupInfo(info.baseInfo),
            groupAlias: info.groupAlias,
            notificationStatus: info.notificationStatus.value(),
        });
    }

    return list;
};

export const mZIMGroupMuteInfo = (info: NZIMGroupMuteInfo) => {
    return {
        mode: info.mode.value(),
        expiredTime: info.expiredTime,
        roles: Array.fromNative(info.roles) as number[],
    } as ZIMGroupMuteInfo;
};

export const mZIMGroupVerifyInfo = (info: NZIMGroupVerifyInfo) => {
    return {
        joinMode: info.joinMode.value(),
        inviteMode: info.inviteMode.value(),
        beInviteMode: info.beInviteMode.value(),
    } as ZIMGroupVerifyInfo;
};

export const mZIMGroupOperatedInfo = (info: NZIMGroupOperatedInfo) => {
    return {
        userID: info.userID,
        userName: info.userName,
        memberRole: info.memberRole,
        memberNickname: info.memberNickname,
    } as ZIMGroupOperatedInfo;
};

export const oZIMUserOrGroupMember = (info: ZIMGroupMemberSimpleInfo): NZIMUserInfo => {
    const obj = new NZIMGroupMemberSimpleInfo();
    obj.userID = info.userID;
    obj.userName = info.userName;
    obj.userAvatarUrl = info.userAvatarUrl;
    obj.memberRole = (info as ZIMGroupMemberSimpleInfo).memberRole as Int;
    obj.memberNickname = (info as ZIMGroupMemberSimpleInfo).memberNickname;
    return obj;
};

export const mZIMUserOrGroupMember = (info: NZIMUserInfo) => {
    const map = {
        userID: info.userID,
        userName: info.userName,
        userAvatarUrl: info.userAvatarUrl,
        memberRole: 0,
        memberNickname: '',
    } as ZIMGroupMemberSimpleInfo;
    if (info instanceof NZIMGroupMemberSimpleInfo) {
        map.memberRole = info.memberRole;
        map.memberNickname = info.memberNickname;
    }
    return map;
};

export const mZIMUserOrGroupMemberList = (infos: ArrayList<NZIMUserInfo>) => {
    const list: ZIMGroupMemberSimpleInfo[] = [];

    for (let i = 0; i < infos.size; i++) {
        list.push(mZIMUserOrGroupMember(infos.get(i as Int))!);
    }

    return list;
};

export const mZIMGroupMemberSimpleInfo = (info: NZIMGroupMemberSimpleInfo) => {
    return {
        userID: info.userID,
        userName: info.userName,
        userAvatarUrl: info.userAvatarUrl,
        memberRole: info.memberRole,
        memberNickname: info.memberNickname,
    } as ZIMGroupMemberSimpleInfo;
};

export const mZIMGroupMemberInfo = (info: NZIMGroupMemberInfo) => {
    const groupEnterInfo: ZIMGroupEnterInfo = {
        enterTime: info.groupEnterInfo.enterTime,
        enterType: info.groupEnterInfo.enterType.value(),
    };
    if (info.groupEnterInfo.operatedUser != null) {
        groupEnterInfo.operatedUser = mZIMGroupMemberSimpleInfo(info.groupEnterInfo.operatedUser!);
    }

    return {
        userID: info.userID,
        userName: info.userName,
        userAvatarUrl: info.userAvatarUrl,
        memberRole: info.memberRole,
        memberNickname: info.memberNickname,
        muteExpiredTime: info.muteExpiredTime,
        groupEnterInfo,
    } as ZIMGroupMemberInfo;
};

export const mZIMGroupMemberInfoList = (infos: ArrayList<NZIMGroupMemberInfo>) => {
    const list: ZIMGroupMemberInfo[] = [];

    for (let i = 0; i < infos.size; i++) {
        list.push(mZIMGroupMemberInfo(infos.get(i as Int)));
    }

    return list;
};

export const mZIMGroupFullInfo = (info: NZIMGroupFullInfo) => {
    const map = {
        baseInfo: mZIMGroupInfo(info.baseInfo),
        groupAlias: info.groupAlias,
        groupNotice: info.groupNotice,
        groupAttributes: mMap(info.groupAttributes),
        notificationStatus: info.notificationStatus.value(),
        createTime: info.createTime,
        maxMemberCount: info.maxMemberCount,
        mutedInfo: mZIMGroupMuteInfo(info.mutedInfo);
        verifyInfo: mZIMGroupVerifyInfo(info.verifyInfo);
    } as ZIMGroupFullInfo;
    return map;
};

export const mZIMGroupApplicationInfoList = (infos: ArrayList<NZIMGroupApplicationInfo>) => {
    const list: ZIMGroupApplicationInfo[] = [];

    for (let i = 0; i < infos.size; i++) {
        const info = infos.get(i as Int);
        const json: ZIMGroupApplicationInfo = {
            type: info.type.value(),
            state: info.state.value(),
            createTime: info.createTime,
            updateTime: info.updateTime,
            wording: info.wording,
            applyUser: mZIMUserInfo(info.applyUser),
            groupInfo: mZIMGroupInfo(info.groupInfo),
        };
        if (info.operatedUser != null) {
            json.operatedUser = mZIMGroupMemberSimpleInfo(info.operatedUser!);
        }
        list.push(json);
    }

    return list;
};

export const mZIMGroupAttributesUpdateInfoList = (infos: ArrayList<NZIMGroupAttributesUpdateInfo>) => {
    const list: ZIMGroupAttributesUpdateInfo[] = [];

    for (let i = 0; i < infos.size; i++) {
        const info = infos.get(i as Int);
        list.push({ action: info.action.value(), groupAttributes: mMap(info.groupAttributes) });
    }

    return list;
};

export const mZIMGroupSearchInfoList = (infos: ArrayList<NZIMGroupSearchInfo>) => {
    const list: ZIMGroupSearchInfo[] = [];

    for (let i = 0; i < infos.size; i++) {
        const info = infos.get(i as Int);
        list.push({
            groupInfo: mZIMGroupInfo(info.groupInfo),
            userList: mZIMGroupMemberInfoList(info.userList),
        });
    }

    return list;
};

// MARK: - Call

export const mZIMCallUserInfoList = (infos: ArrayList<NZIMCallUserInfo>) => {
    const list: ZIMCallUserInfo[] = [];

    for (let i = 0; i < infos.size; i++) {
        const info = infos.get(i as Int);
        list.push({
            userID: info.userID,
            state: info.state.value(),
            extendedData: info.extendedData,
        });
    }

    return list;
};

export const mZIMCallInfoList = (infos: ArrayList<NZIMCallInfo>) => {
    const list: ZIMCallInfo[] = [];

    for (let i = 0; i < infos.size; i++) {
        const info = infos.get(i as Int);
        list.push({
            callID: info.callID,
            caller: info.caller,
            mode: info.mode.value(),
            state: info.state.value(),
            extendedData: info.extendedData,
            createTime: info.createTime,
            endTime: info.endTime,
            callUserList: mZIMCallUserInfoList(info.callUserList),
        });
    }

    return list;
};

// MARK: - Friend

export const mZIMFriendInfo = (info: NZIMFriendInfo) => {
    return {
        userID: info.userID,
        userName: info.userName,
        userAvatarUrl: info.userAvatarUrl,
        wording: info.wording,
        createTime: info.createTime,
        friendAlias: info.friendAlias,
        friendAttributes: mMap(info.friendAttributes),
    } as ZIMFriendInfo;
};

export const mZIMFriendInfoList = (infos: ArrayList<NZIMFriendInfo>) => {
    const list: ZIMFriendInfo[] = [];

    for (let i = 0; i < infos.size; i++) {
        list.push(mZIMFriendInfo(infos.get(i as Int)));
    }

    return list;
};

export const mZIMFriendRelationInfoList = (infos: ArrayList<NZIMFriendRelationInfo>) => {
    const list: ZIMFriendRelationInfo[] = [];

    for (let i = 0; i < infos.size; i++) {
        const info = infos.get(i as Int);
        list.push({ userID: info.userID, type: info.type.value() });
    }

    return list;
};

export const mZIMFriendApplicationInfo = (info: NZIMFriendApplicationInfo) => {
    return {
        applyUser: mZIMUserInfo(info.applyUser),
        wording: info.wording,
        createTime: info.createTime,
        updateTime: info.updateTime,
        type: info.type.value(),
        state: info.type.value(),
    } as ZIMFriendApplicationInfo;
};

export const mZIMFriendApplicationInfoList = (infos: ArrayList<NZIMFriendApplicationInfo>) => {
    const list: ZIMFriendApplicationInfo[] = [];

    for (let i = 0; i < infos.size; i++) {
        list.push(mZIMFriendApplicationInfo(infos.get(i as Int)));
    }

    return list;
};
