/**
 * 环信 SDK 统一入口
 */

export * from './interface.uts';
// #ifdef APP-ANDROID
export { 
  initSDK, 
  addConnectionListener,
  removeConnectionListener,
  removeAllConnectionListeners,
  ConnectionListenerCallbacks,
  loginSDK,
  loginSDKWithToken,
  loginSDKWithAgoraToken,
  logoutSDK,
  logoutSDKSync,
  getCurrentUser,
  isLoggedInBefore,
  isConnected,
  isLoggedIn
} from './app-android/index.uts';
// #endif
