/**
 * 环信IM SDK - 接口定义
 */

/**
 * 初始化参数
 */
export interface EMInitParam {
  appKey: string
  debugMode?: boolean
}

/**
 * 登录参数
 */
export interface EMLoginParam {
  username: string
  password: string
}

/**
 * 消息体
 */
export interface EMMessageBody {
  type: string
  content?: string
}

/**
 * 消息
 */
export interface EMMessage {
  messageId: string
  conversationId: string
  from: string
  to: string
  direction: number
  status: number
  timestamp: number
  localTime: number
  body: EMMessageBody
}
